---
version: 2.1

orbs:
  terraform: feedyard/terraform@0.6.0

# git push: deploy sandbox, also run sandbox deploy on taint-tag
on-push-master: &on-push-master
  branches:
    only: /master/
  tags:
    only: /.*-taint$/

# git tag: release to preview cluster
on-tag-master: &on-tag-master
  branches:
    ignore: /.*/
  tags:
    only: /.*/

commands:

  set-environment:
    description: generate environment credentials and configuration from templates
    parameters:
      cluster:
        type: string
        default: ''
    steps:
      - run:
          name: set ~/.terraformrc
          command: secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
      - run:
          name: set << parameters.cluster >> environment variables
          command: |
            secrethub inject -i environments/<< parameters.cluster >>.auto.tfvars.json.tpl -o << parameters.cluster >>.auto.tfvars.json

  set-kubeconfig:
    parameters:
      cluster:
        description: cluster name to use for configuration
        type: string
        default: ""
    steps:
      - run:
          name: setup kubeconfig and deploy core services
          command: |
            mkdir -p ~/.kube
            SECRETHUB_VAR_ENV=<< parameters.cluster >> secrethub inject -i tpl/kubeconfig.tpl -o ~/.kube/config

  deploy-core-services:
    parameters:
      cluster:
        description: cluster name to use for configuration
        type: string
        default: ""
    steps:
      - run:
          name: deploy standard, non-istio administrative namespaces
          command: kubectl apply -f standard-namespaces.yaml
      - run:
          name: deploy metrics apis
          command: kubectl apply -f metrics-apis --recursive
      - run:
          name: deploy cluster-autoscaler
          command: bash scripts/deploy_cluster_autoscaler.sh << parameters.cluster >>
      - run:
          name: deploy containter-insights
          command: bash scripts/deploy_cloud_watch.sh << parameters.cluster >>

  validate-cluster:
    parameters:
      cluster:
        description: cluster name to use for configuration
        type: string
        default: ""
      sonobuoy-mode:
        type: string
        default: quick
    steps:
      - run:
          name: cis benchmarks
          command: bash scripts/kube_bench.sh << parameters.cluster >>
      - run:
          name: conformance smoke-test
          command: bash scripts/sonobuoy_conformance_test.sh << parameters.cluster >> << parameters.sonobuoy-mode >>
      - run:
          name: validate deploy-core-services health
          command: bats test

  validate-eks:
    parameters:
      cluster:
        type: string
        default: ''
    steps:
      - run:
          name: use kubeconfig just written by tf apply
          command: |
            mkdir -p ~/.kube
            cp kubeconfig_<< parameters.cluster >> ~/.kube/config
      - run:
          name: test eks configuration
          environment:
            TEST_ENV: << parameters.cluster >>
          command: bash scripts/cluster_configuration_tests.sh << parameters.cluster >>

  check-taint:
    description: evaluate and apply node taint for updates
    parameters:
      node-group:
        type: string
        default: ''
      plan-or-apply:
        description: is this a terraform plan or apply phase?
        type: string
        default: 'plan'
    steps:
      - run:
          name: Schedule for terraform taint if -taint in tag
          command: bash scripts/taint_node_groups.sh << parameters.node-group >> << parameters.plan-or-apply >>

  store-system-credentials:
    parameters:
      cluster:
        type: string
        default: ''
    steps:
      - run:
          name: write cluster oidc-assume-role kubeconfig
          command: bash scripts/write_cluster_credentials.sh << parameters.cluster >>

  validate-and-configure-cluster:
    parameters:
      cluster:
        description: cluster being validated
        type: string
        default: ""
      sonobuoy-mode:
        description: sonobuoy test mode
        type: string
        default: quick
    steps:
      - validate-eks:
          cluster: << parameters.cluster >>
      - store-system-credentials:
          cluster: << parameters.cluster >>
      - deploy-core-services:
          cluster: << parameters.cluster >>
      - validate-cluster:
          cluster: << parameters.cluster >>
          sonobuoy-mode: << parameters.sonobuoy-mode >>


workflows:
  version: 2
  lab-platform-eks-pipeline:

    jobs:
      - terraform/plan:
          name: sandbox-change-plan
          context: twdps-core-labs-team
          shell: secrethub run --env-file secrethub.nonprod.env -- /bin/sh -eo pipefail
          workspace: sandbox
          before-terraform:
            - set-environment:
                cluster: sandbox
          after-terraform-init:
            - check-taint:
                node-group: group_a
                plan-or-apply: plan
          filters: *on-push-master

      - approve-sandbox-changes:
          type: approval
          requires:
            - sandbox-change-plan
          filters: *on-push-master

      - terraform/apply:
          name: sandbox-change-apply
          context: twdps-di
          shell: secrethub run --env-file secrethub.nonprod.env -- /bin/sh -eo pipefail
          workspace: sandbox
          before-terraform:
            - set-environment:
                cluster: sandbox
          after-terraform-init:
            - check-taint:
                node-group: group_a
                plan-or-apply: apply
          after-terraform:
            - validate-and-configure-cluster:
                cluster: sandbox
                sonobuoy-mode: quick
          requires:
            - approve-sandbox-changes
          filters: *on-push-master

      # release
      - terraform/plan:
          name: preview-change-plan
          context: twdps-core-labs-team
          shell: secrethub run --env-file secrethub.nonprod.env -- /bin/sh -eo pipefail
          workspace: preview
          before-terraform:
            - set-environment:
                cluster: preview
          after-terraform-init:
            - check-taint:
                node-group: group_a
                plan-or-apply: plan
          filters: *on-tag-master

      - approve-preview-changes:
          type: approval
          requires:
            - preview-change-plan
          filters: *on-tag-master

      - terraform/apply:
          name: preview-change-apply
          context: twdps-di
          shell: secrethub run --env-file secrethub.nonprod.env -- /bin/sh -eo pipefail
          workspace: preview
          before-terraform:
            - set-environment:
                cluster: preview
          after-terraform-init:
            - check-taint:
                node-group: group_a
                plan-or-apply: apply
          after-terraform:
            - validate-and-configure-cluster:
                cluster: preview
                sonobuoy-mode: quick
          requires:
            - approve-preview-changes
          filters: *on-tag-master
