---
version: 2.1

orbs:
  terraform: twdps/terraform@0.4.0
  # can override kubectl, awspec versions as necessary
  kube: twdps/kube-ops@dev:latest
  # used for github-release-notes feature
  executor-tools: twdps/executor-tools@0.2.0

# ==== global pipeline parameters

parameters:
  context:
    description: circleci context for all jobs
    type: string
    default: twdps-core-labs-team
  shell-options:
    description: shell options for all jobs
    type: string
    default: secrethub run --env-file secrethub.nonprod.env -- /bin/bash -eo pipefail
  terraform-version:
    description: terraform version for all jobs
    type: string
    default: "1.1.3"
  executor-image:
    description: image to use for terraform runs
    type: string
    default: twdps/circleci-kube-ops:alpine-0.4.0

# git push: deploy sandbox
on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

# git tag: release to preview cluster
on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

commands:

  set-environment:
    description: generate environment credentials and configuration from templates
    parameters:
      cluster:
        type: string
    steps:
      - run:
          name: set ~/.terraformrc
          command: secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
      - run:
          name: set << parameters.cluster >> environment variables
          command: |
            secrethub inject -i environments/<< parameters.cluster >>.auto.tfvars.json.tpl -o << parameters.cluster >>.auto.tfvars.json
  
  set-kubeconfig:
    parameters:
      cluster:
        description: cluster name to use for configuration
        type: string
    steps:
      - run:
          name: setup kubeconfig
          command: |
            mkdir -p ~/.kube
            SECRETHUB_VAR_ENV=<< parameters.cluster >> secrethub inject -i tpl/kubeconfig.tpl -o ~/.kube/config

  taint-node-group:
    description: apply node taint for automatic lastest eks-optimized-al2 managed node ami updates
    parameters:
      node-group:
        type: string
    steps:
      - run:
          name: set terraform taint on managed node group to cause new node template with latest ami version
          command: terraform taint "module.eks.module.node_groups.aws_eks_node_group.workers[\"<< parameters.node-group >>\"]"

  store-system-credentials:
    parameters:
      cluster:
        type: string
    steps:
      - run:
          name: write cluster oidc-assume-role kubeconfig
          command: bash scripts/write_cluster_credentials.sh << parameters.cluster >>

jobs:

  post-terraform-configuration:
    parameters:
      cluster:
        description: cluster being validated
        type: string
    docker:
      - image: << pipeline.parameters.executor-image >>
    shell: << pipeline.parameters.shell-options >>
    steps:
      - checkout
      - setup_remote_docker
      - set-environment:
          cluster: << parameters.cluster >>
      - set-kubeconfig:
          cluster: << parameters.cluster >>
      - run:
          name: configure ENI environment parameters
          command: kubectl set env ds aws-node -n kube-system WARM_IP_TARGET=15
      - run:
          name: rolling restart of aws-node to use environment parameters
          command: kubectl rollout restart ds aws-node -n kube-system

  validate-eks:
    parameters:
      cluster:
        description: cluster being validated
        type: string
    docker:
      - image: << pipeline.parameters.executor-image >>
    shell: << pipeline.parameters.shell-options >>
    steps:
      - checkout
      - setup_remote_docker
      - set-environment:
          cluster: << parameters.cluster >>
      - set-kubeconfig:
          cluster: << parameters.cluster >>
      - run:
          name: test eks configuration
          environment:
            TEST_ENV: << parameters.cluster >>
          command: bash scripts/eks_configuration_tests.sh << parameters.cluster >>
      - kube/cis-benchmarks:
          benchmark: eks
          namespace: default

 # compare desired eks component verions with current release versions
  version-check:
    parameters:
      cluster:
        description: cluster being checked
        type: string
    docker:
      - image: << pipeline.parameters.executor-image >>
    shell: << pipeline.parameters.shell-options >>
    steps:
      - checkout
      - setup_remote_docker
      - set-environment:
          cluster: << parameters.cluster >>
      - set-kubeconfig:
          cluster: << parameters.cluster >>
      - run:
          name: test addon and managed node group ami versions
          command: bash scripts/check_eks_and_addon_versions.sh << parameters.cluster >>

workflows:
  version: 2

  lab-platform-eks-base-pipeline:
    jobs:
      # sandbox cluster
      - terraform/plan:
          name: sandbox-change-plan
          context: << pipeline.parameters.context >>
          shell: << pipeline.parameters.shell-options >>
          workspace: sandbox
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment:
                cluster: sandbox
          filters: *on-push-main

      - approve-sandbox-changes:
          type: approval
          requires:
            - sandbox-change-plan
          filters: *on-push-main

      - terraform/apply:
          name: apply-sandbox-changes
          context: << pipeline.parameters.context >>
          shell: << pipeline.parameters.shell-options >>
          workspace: sandbox
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment:
                cluster: sandbox
          after-terraform-init:
            - taint-node-group:
                node-group: group_a
          after-terraform:
            - store-system-credentials:
                cluster: sandbox
          requires:
            - approve-sandbox-changes
          filters: *on-push-main

      - post-terraform-configuration:
          name: post-terraform-sandbox-configuration
          context: << pipeline.parameters.context >>
          cluster: sandbox
          requires:
            - apply-sandbox-changes
          filters: *on-push-main

      - validate-eks:
          name: validate-sandbox-cluster
          context: << pipeline.parameters.context >>
          cluster: sandbox
          requires:
            - post-terraform-sandbox-configuration
          filters: *on-push-main

      # preview cluster
      - terraform/plan:
          name: preview-change-plan
          context: << pipeline.parameters.context >>
          shell: << pipeline.parameters.shell-options >>
          workspace: preview
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment:
                cluster: preview
          filters: *on-tag-main

      - approve-preview-changes:
          type: approval
          requires:
            - preview-change-plan
          filters: *on-tag-main

      - terraform/apply:
          name: apply-preview-changes
          context: << pipeline.parameters.context >>
          shell: << pipeline.parameters.shell-options >>
          workspace: preview
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment:
                cluster: preview
          after-terraform-init:
            - taint-node-group:
                node-group: group_a
          after-terraform:
            - store-system-credentials:
                cluster: preview
          requires:
            - approve-preview-changes
          filters: *on-tag-main

      - post-terraform-configuration:
          name: post-terraform-preview-configuration
          context: << pipeline.parameters.context >>
          cluster: preview
          requires:
            - apply-preview-changes
          filters: *on-tag-main

      - validate-eks:
          name: validate-preview-cluster
          context: << pipeline.parameters.context >>
          cluster: preview
          requires:
            - post-terraform-preview-configuration
          filters: *on-tag-main

  generate-release-notes:
    jobs:
      - executor-tools/release:
          name: release-lab-platform-eks
          context: << pipeline.parameters.context >>
          shell: << pipeline.parameters.shell-options >>
          filters: *on-tag-main

  # perform the pipeline health checks and compare desired eks component verions with current release versions
  nightly-validation:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - validate-eks:
          name: validate-sandbox-cluster
          context: << pipeline.parameters.context >>
          cluster: sandbox
      - version-check:
          name: check-sandbox-addon-and-ami-versions
          context: << pipeline.parameters.context >>
          cluster: sandbox
      - validate-eks:
          name: validate-preview-cluster
          context: << pipeline.parameters.context >>
          cluster: preview
      - version-check:
          name: check-preview-addon-and-ami-versions
          context: << pipeline.parameters.context >>
          cluster: preview
